server:
  port: 5000
spring:
  datasource:
    url: jdbc:h2:mem:vehicles
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
logging:
  level:
    org.springframework.web: debug
    org.springframework.web.servlet.mvc.method.annotation: info